<?php

/**
 * @file
 * Contains challenge.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function challenge_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the challenge module.
    case 'help.page.challenge':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Challenge Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function challenge_theme() {
  return [
    'challenge' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function challenge_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if ($form_id == 'node_company_edit_form' || $form_id == 'node_company_form') {
        $form['#validate'][] = 'company_email_validate';
    }
}

function company_email_validate(&$form, FormStateInterface $form_state) {
    $value = $form_state->getValue('field_email_contact');
    $input = $value[0]['value'];

    $without_domain = strstr($input, '@', true);

    if ($without_domain == "no-reply" || $without_domain == 'noreply') {
        $form_state->setErrorByName('field_email_contact', t('Please enter a valid response email.'));
    }
}

